// Generated by CoffeeScript 1.7.1
(function() {
  var DEFAULTS, FileServer, Validator, fileServer, fs, http, mime, path, settings, url, validator;

  http = require('http');

  url = require('url');

  path = require('path');

  fs = require('fs');

  mime = require('mime');

  DEFAULTS = {
    PORT: 8000,
    DIRECTORY: process.cwd(),
    CLIENT_DIR: 'client'
  };

  FileServer = (function() {
    FileServer.prototype.dirRegex = new RegExp('^/dir/([^\0]*)$');

    FileServer.prototype.fileRegex = new RegExp('^/file/([^\0]+)$');

    function FileServer(settings) {
      this.publicDir = settings.directory;
      this.port = settings.port;
      this.clientDir = settings.clientDir;
    }

    FileServer.prototype.startServer = function() {
      http.createServer((function(_this) {
        return function(req, res) {
          var regexMatch, socketData, timeOfRequest, uri;
          uri = url.parse(req.url).pathname;
          uri = unescape(uri);
          socketData = req.socket.address();
          timeOfRequest = _this.getCurrentTime();
          console.log("" + socketData.address + " - " + timeOfRequest + " \"" + req.method + " " + uri + "\"");
          regexMatch = _this.dirRegex.exec(uri);
          if (regexMatch !== null) {
            _this.checkDirExistenceAndHandle(regexMatch[1], res);
            return;
          }
          regexMatch = _this.fileRegex.exec(uri);
          if (regexMatch !== null) {
            _this.checkFileExistenceAndHandle(regexMatch[1], res);
            return;
          }
          _this.checkClientFileExistenceAndHandle(uri, res);
        };
      })(this)).listen(this.port);
      console.log("Server serving on port " + this.port);
      return console.log("Folder used: " + this.publicDir);
    };

    FileServer.prototype.checkClientFileExistenceAndHandle = function(uri, res) {
      var realPath;
      if (uri === '/') {
        uri = 'index.html';
      }
      realPath = this.convertPath(this.clientDir, uri);
      if (!realPath) {
        this.sendErrorNotFound(res);
        return;
      }
      fs.stat(realPath, (function(_this) {
        return function(err, stats) {
          if (err) {
            _this.sendErrorInternal(res);
          } else if (stats.isDirectory()) {
            _this.sendErrorInternal(res);
          } else {
            _this.sendFile(realPath, res);
          }
        };
      })(this));
    };

    FileServer.prototype.convertPath = function(parentDir, uri) {
      var realPath;
      realPath = path.join(parentDir, uri);
      realPath = path.normalize(realPath);
      if (realPath.indexOf(parentDir) !== 0) {
        return false;
      }
      if (fs.existsSync(realPath)) {
        return realPath;
      } else {
        return false;
      }
    };

    FileServer.prototype.checkDirExistenceAndHandle = function(uri, res) {
      var realPath;
      realPath = this.convertPath(this.publicDir, uri);
      if (!realPath) {
        this.sendErrorNotFound(res);
        return;
      }
      fs.stat(realPath, (function(_this) {
        return function(err, stats) {
          if (err) {
            _this.sendErrorInternal(res);
          } else if (stats.isDirectory()) {
            _this.sendDirContents(realPath, res);
          } else {
            _this.sendErrorNotFound(res);
          }
        };
      })(this));
    };

    FileServer.prototype.checkFileExistenceAndHandle = function(uri, res) {
      var realPath;
      realPath = this.convertPath(this.publicDir, uri);
      if (!realPath) {
        this.sendErrorNotFound(res);
        return;
      }
      fs.stat(realPath, (function(_this) {
        return function(err, stats) {
          if (err) {
            _this.sendErrorInternal(res);
          } else if (stats.isFile()) {
            _this.sendFile(realPath, res);
          } else {
            _this.sendErrorNotFound(res);
          }
        };
      })(this));
    };

    FileServer.prototype.sendDirContents = function(realPath, res) {
      fs.readdir(realPath, (function(_this) {
        return function(err, files) {
          var dataToSend, fileSize, fileStats, i, isDir, uri, uriStart, _i, _ref;
          if (err) {
            _this.sendErrorInternal(res);
            return;
          }
          dataToSend = [];
          for (i = _i = 0, _ref = files.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
            fileStats = fs.statSync(path.join(realPath, files[i]));
            isDir = fileStats.isDirectory();
            uriStart = realPath.replace(_this.publicDir, '/');
            if (isDir) {
              fileSize = 0;
            } else {
              fileSize = fileStats.size;
            }
            uri = path.join(uriStart, files[i]);
            if (isDir) {
              uri += '/';
            }
            dataToSend[i] = {
              name: files[i],
              uri: uri,
              isDir: isDir,
              size: fileSize
            };
          }
          res.writeHead(200, {
            'Content-Type': 'application/json'
          });
          res.write(JSON.stringify(dataToSend));
          return res.end();
        };
      })(this));
    };

    FileServer.prototype.sendFile = function(filepath, res) {
      var stream;
      stream = fs.createReadStream(filepath);
      res.writeHead(200, {
        'Content-Type': mime.lookup(filepath)
      });
      stream.pipe(res, {
        end: true
      });
    };

    FileServer.prototype.sendErrorNotFound = function(res) {
      res.writeHead(404);
      return res.end();
    };

    FileServer.prototype.sendErrorInternal = function(res) {
      res.writeHead(500);
      return res.end();
    };

    FileServer.prototype.getCurrentTime = function() {
      var currentTime;
      currentTime = new Date();
      return '[' + currentTime.getFullYear() + '-' + (currentTime.getMonth() + 1) + '-' + (currentTime.getDate()) + ' ' + (currentTime.getHours()) + ':' + (currentTime.getMinutes()) + ':' + currentTime.getSeconds() + ']';
    };

    return FileServer;

  })();

  Validator = (function() {
    function Validator() {}

    Validator.prototype.validateArgs = function() {
      var dir, port;
      dir = process.argv[2] || DEFAULTS.DIRECTORY;
      dir = path.resolve(dir, DEFAULTS.DIRECTORY);
      port = process.argv[3] || DEFAULTS.PORT;
      if (this.validatePathPort(dir, port)) {
        return {
          directory: dir,
          port: port,
          clientDir: DEFAULTS.CLIENT_DIR
        };
      }
      return false;
    };

    Validator.prototype.validatePathPort = function(dirpath, port) {
      if (!this.validateDir(dirpath)) {
        console.log('Directory path is bad');
        return false;
      }
      if (!this.validatePort(port)) {
        console.log('Port must be a number between 0 to 65535');
        return false;
      }
      return true;
    };

    Validator.prototype.validateDir = function(dirpath) {
      if (fs.existsSync(dirpath)) {
        return fs.statSync(dirpath).isDirectory();
      }
      return false;
    };

    Validator.prototype.validatePort = function(port) {
      var num;
      num = parseInt(port);
      if (isNaN(num)) {
        return false;
      }
      return num >= 0 && num <= 65535;
    };

    return Validator;

  })();

  validator = new Validator();

  settings = validator.validateArgs();

  if (settings) {
    fileServer = new FileServer(settings);
    fileServer.startServer();
  }

}).call(this);
